spring:
  application:
    name: auth-service


eureka:
  client:
    service-url:
        defaultZone: http://discovery-service:8061/eureka/

management:
  endpoints:
    web:
      exposure:
        include: health

token:
  signing:
    key: bXlT3cQ7GQ9PTeRHz0kF8FlqKuoZQzP4Vbq4YlU1sjI=

tdelivery:
  user-service:
    url: http://user-service:8083/users

server:
  port: 8081