spring:
  application:
    name: auth-service

cloud:
  eureka:
    client:
      service-url:
        defaultZone: http://discovery-service:8761/eureka/
      register-with-eureka: true
      fetch-registry: true

token:
  signing:
    key: bXlT3cQ7GQ9PTeRHz0kF8FlqKuoZQzP4Vbq4YlU1sjI=

tdelivery:
  user-service:
    url: http://user-service:8083/users

server:
  port: 8081