spring:
  application:
    name: message-service
  mail:
    host: smtp.gmail.com
    port: 587
    username: "YOUR EMAIL"
    password: "YOUR PASSWORD FOR EMAIL"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  kafka:
    bootstrap-servers: localhost:29092
    consumer:
      group-id: message-group
      auto-offset-reset: earliest

messageService:
  url: http://localhost:8085/message/sendMessage
  topic: order-message

server:
  port: 8085