spring:
  application:
    name: message-service
  mail:
    host: smtp.gmail.com
    port: 587
    username: addressOfYour@gmail.com
    password: password of your gmail
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  kafka:
    bootstrap-servers: kafka:29092
    consumer:
      group-id: message-group
      auto-offset-reset: earliest

management:
  endpoints:
    web:
      exposure:
        include: health

messageService:
  url: http://message-service:8085/message/sendMessage
  topic: order-message

server:
  port: 8085