spring:
  application:
    name: auth-service
  datasource:
#    url: jdbc:postgresql://postgresql_db:5432/auth_db
    url: jdbc:postgresql://localhost:5433/auth_db
    driver-class-name: org.postgresql.Driver
    username: irmag
    password: 123
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always


eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    hostname: localhost

token:
  signing:
    key: 53A73E5F1C4E0A2D3B5F2D784E6A1B423D6F247D1F6E5C3A596D635A75327855

server:
  port: 8081