spring:
  application:
    name: discovery-service
  cloud:
    discovery:
      enabled: true
    eureka:
      client:
        register-with-eureka: false
        fetch-registry: false
      server:
        enable-self-preservation: false

management:
  endpoints:
    web:
      exposure:
        include: health


server:
  port: 8761
