spring:
  application:
    name: order-service
  datasource:
    url: jdbc:postgresql://localhost:5434/order_db
    driver-class-name: org.postgresql.Driver
    username: irmag
    password: 123
  jpa:
    hibernate:
      ddl-auto: create-drop
      dialect: org.hibernate.spatial.dialect.postgis.PostgisDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always
  kafka:
    bootstrap-servers: localhost:29092
    consumer:
      group-id: order-group
      auto-offset-reset: earliest
  transaction:
    default-timeout: 30s
server:
  port: 8084

tdelivery:
  userService:
    url: http://localhost:8083/users/getUsernameAndEmailByID
  messageService:
    url: http://localhost:8085/message/sendMessage
    topic: order-message
  route-service:
    url: http://localhost:8087/delivery/calculate