spring:
  application:
    name: courier-service
  kafka:
    bootstrap-servers: localhost:29092
    consumer:
      group-id: order-group
      auto-offset-reset: earliest

server:
  port: 8086

tdelivery:
  message-topic: courier-topic
  order-service:
    url: http://localhost:8084/order/nearestOrder
    changeStatusUrl: http://localhost:8084/order/changeStatus
  route-service:
    url: http://localhost:8087/delivery/closestOrder