spring:
  application:
    name: courier-service
  kafka:
    bootstrap-servers: kafka:29092
    consumer:
      group-id: order-group
      auto-offset-reset: earliest

server:
  port: 8086

tdelivery:
  message-topic: courier-topic
  order-service:
    url: http://order-service:8084/order/nearestOrder
    changeStatusUrl: http://order-service:8084/order/courier/takeOrder
  route-service:
    url: http://route-service:8087/delivery/closestOrder