spring:
  application:
    name: menu-service
  data:
    mongodb:
      uri: mongodb://menu-service-mongodb:27017/menu-service

server:
  port: 8082

cloud:
  eureka:
    client:
      service-url:
        defaultZone: http://discovery-service:8761/eureka/
      register-with-eureka: true
      fetch-registry: true

management:
  endpoints:
    web:
      exposure:
        include: health


products:
  hardees:
    path: /data/products_hardees.json
  kfc:
    path: /data/products_kfc.json